### ISSUE TITLE
Decimals are always 00 in Big Sur

### ISSUE THREAD

**Issue by Kyle-sandeman-mrdfood** [elegracer/NetSpeedMonitor#11]
Good day, thank you for this very nice tool. (which works unlike others I've tried off of app store).
Currently I see numbers like `1.00 KB/s` however the decimal portion is never above `00`. I do not know if this is limited to big sur.  
Perhaps an option to set precision? Or an option to have MB/s instead (e.g. `15.00 KB/s` -> `0.02 MB/s`)

**Comment by shameer99** [comment]
Seeing the same here for upload, but download properly updates to the hundredths.

**Comment by Kyle-sandeman-mrdfood** [comment]
Hi, indeed at some point this was fixed, thanks!
