### ISSUE TITLE
Please add support for HoRNDIS Interface

### ISSUE THREAD

**Issue by yukenz** [elegracer/NetSpeedMonitor#13]
![Screen Shot 2023-06-09 at 10 10 10](https://github.com/elegracer/NetSpeedMonitor/assets/34228964/7419e04f-d8fb-4028-894b-23c224bfb9b3)

As shown in the picture above, the speed monitor does not show the actual bandwidth through the RNDIS Interface.

**Comment by elegracer** [comment]
Sorry, I'm not an expert in network programming. Pull requests are welcomed if you can implement this, thank you!
