### ISSUE TITLE
[RFE] option for refresh interval

### ISSUE THREAD

**Issue by mailinglists35** [elegracer/NetSpeedMonitor#15]
It would be very useful to be able to lower the refresh interval. One second currently default is too fast for my eyes. Able to set 2,3,5,10 seconds would be very helpful.

If given a single choice, I think 4 seconds would be a good compromise.

**Comment by ashwingopalsamy** [comment]
I agree. Please consider, @elegracer 👀

**Comment by elegracer** [comment]
Thank you! Since I've been paying attention to other fields, I don't have much time updating this tool. Sorry about that!

Been considering your kind suggestions recently. When I have some spare time, I will implement those functions!

**Comment by elegracer** [comment]
Feature implemented in v1.6 as you can see in the latest release.
