### ISSUE TITLE
Start at login not work

### ISSUE THREAD

**Issue by lemos1235** [elegracer/NetSpeedMonitor#16]
macos sequoia 15.1.1
m1 chip

**Comment by elegracer** [comment]
I upgraded my intel mbp to 15.1.1 and everything works well.
Since I don't have a m1 chip one, it's not possible for me to reproduce this bug.
Maybe uninstall this app and reinstall it and try again? If this issue still exists, let me konw! Thanks!

**Comment by lemos1235** [comment]
Reinstalled and it's fixed now.

**Comment by lemos1235** [comment]
But after rebooting, the internet speed was not displayed in real-time; the speed still showed 0. It only returned to normal after restarting.
