### ISSUE TITLE
Causing high cpu consumption of system

### ISSUE THREAD

**Issue by GeekZJJ** [elegracer/NetSpeedMonitor#4]
Software version: `1.2`, downloaded from release page
System version: `10.14.6(18G2022)`
Problem: After starting this app, the utilization of CPU(i5-8265u) is about 25%-30%, which makes the cpu stuck at high frequency(3GHz+) and consume a lot of energy. I take a look at the `Activity Monitor` app, and the cpu usage of this app is quite low. So the `nettop` command maybe the root cause.
Screenshot:
![image](https://user-images.githubusercontent.com/10358410/75945162-7196b000-5ed4-11ea-973d-eeedab9a8576.png)

**Comment by elegracer** [comment]
That's right, using `nettop` is not a cpu efficient way of monitoring network bandwidth, and I'm looking for new solution to this. Right now I have to leave it as it is.

**Comment by GeekZJJ** [comment]
Got it. Thanks for developing this App.😆

**Comment by elegracer** [comment]
A more cpu-efficient method is used now, please check the new release, and let me know if there's any problem.

**Comment by GeekZJJ** [comment]
Sorry for my late to see this. I have tried it out just now. Very nice. Great work~😄
