### ISSUE TITLE
当电脑进入睡眠状态后crash

### ISSUE THREAD

**Issue by paradiseduo** [elegracer/NetSpeedMonitor#5]
![image](https://user-images.githubusercontent.com/14846965/77222145-a28d0b00-6b8b-11ea-96db-4dbca2c21501.png)
Double(cell[2])是nill，强制解包一个nill导致崩溃

**Comment by elegracer** [comment]
出于cpu占用较高的原因，我已经选择了一个更加cpu友好的方案，如果还出现了类似的问题，请联系我。
