### ISSUE TITLE
网速变化时菜单的位置也变化

### ISSUE THREAD

**Issue by Yriuns** [elegracer/NetSpeedMonitor#6]
<img width="620" alt="Screen Shot 2020-04-06 at 23 25 54" src="https://user-images.githubusercontent.com/13610387/78575468-fc652480-785d-11ea-8ef9-8886500be720.png">
1. 两张图右对齐应该会更美观
2. 不了解菜单栏的字体是否能够自定义，如果可以的话能否采用等宽字体？

**Comment by elegracer** [comment]
由于`NSFont.monospacedSystemFont`只有在10.15之后才可以用，所以之前用的是`NSFont.monospacedDigitSystemFont`。

现在改为`Menlo`了，不过因为字体的原因，箭头换掉了。

对应commit为<https://github.com/elegracer/NetSpeedMonitor/commit/becff08f7675ca1906f8aecb3d3fc307e0e42941>，由于自带的等宽字体比较少，选了几个发现这个算能看的，你可以多试几个，如果有更好的，请联系我，谢谢！

**Comment by elegracer** [comment]
又做了一个更新<https://github.com/elegracer/NetSpeedMonitor/commit/c9e117f1173db65d7484245e9a6bc6a2bd6603c3>，并且把预编译的app放到新的release里面，[NetSpeedMonitor 1.4](https://github.com/elegracer/NetSpeedMonitor/releases/tag/1.4)里面。

这一次直接嵌入并使用了`SFMono-Regular.otf`，能够完美地实现右对齐，自测没有任何问题，如果你遇到任何问题，请联系我，谢谢。

**Comment by Yriuns** [comment]
神速更新！
我个人觉得效果很好🤩不会左右跳动了，KB和MB也一样宽
